src/objects/PEP_Patient__c.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Stores the Gender of the patient.</description>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Prefer not to answer</fullName>
                    <default>true</default>
                    <label>Prefer not to answer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>PEP-{000000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TEST_PEP_Patient_Create_Controller.cls
@isTest
public with sharing class TEST_PEP_Patient_Create_Controller{
    public static testmethod void testInsertPatient(){
        test.startTest();
        PEP_Patient__c pat = new PEP_Patient__c();
        pat.Gender__c = 'Male';
        insert pat ;
        system.assertEquals(pat.Gender__c,'Male');
        
        ApexPages.StandardController sc = new ApexPages.StandardController(pat);
        PEP_Patient_Create_Controller  cntrl= new PEP_Patient_Create_Controller(sc);
        
        PageReference pageRef = Page.PEP_Patient_Create;
        pageRef.getParameters().put('id', String.valueOf(pat.Id));
        Test.setCurrentPage(pageRef);
        cntrl.saveDetails();
        Test.StopTest();
    }

}