src/objects/PEP_Patient__c.object
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PEP-{000000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PEP_Patient_Address__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <label>Patient</label>
        <referenceTo>PEP_Patient__c</referenceTo>
        <relationshipLabel>Patient Addresses</relationshipLabel>
        <relationshipName>Patient_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Patient Address</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Patient Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PEP_Patient_Create_Controller.cls
/*********************************************************************************************************
Class Name      : PEP_Patient_Create_Controller
Description     : Controller for Patient Enrollment Form
Created By      : Abhinav Gadepalli
Created Date    : Feb 28, 2018
Modification Log:
--------------------------------------------------------------------------------------------------------------
Developer                     Date                      Description
--------------------------------------------------------------------------------------------------------------
Abhinav Gadepalli             Feb 28, 2018              Initial Version
****************************************************************************************************************/
public with sharing class PEP_Patient_Create_Controller{
    
    public PEP_Patient__c patientRecord {get; set;}
    public PEP_Patient_Address__c patientAddressRecord {get; set;}
    
    public PEP_Patient_Create_Controller(ApexPages.StandardController controller) {
        patientRecord = new PEP_Patient__c();
        patientAddressRecord = new PEP_Patient_Address__c();
    }
    
    public PageReference saveDetails(){
        insert patientRecord;
        patientAddressRecord.Patient__c = patientRecord.Id;
        insert patientAddressRecord;
        PageReference pg = new PageReference('/'+patientRecord.Id);
        pg.setRedirect(true);
        return pg;
    }
}